[platformio]
src_dir = src
default_envs = xiao_esp32c6

[env]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.32
framework = arduino
monitor_speed = 115200

; Libraries
lib_deps =
    ; ESP-NOW is built into the ESP32 Arduino framework

[env:xiao_esp32c6]
board = seeed_xiao_esp32c6
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_XIAO_ESP32C6

[env:adafruit_feather_esp32_v2]
board = adafruit_feather_esp32_v2
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_ESP32_WROOM

; Per-robot deployment environments
[env:cheep]
board = adafruit_feather_esp32_v2
build_flags =
    -DBOARD_ESP32_WROOM
    -DDROID_CHEEP
build_type = release

[env:ke4]
board = seeed_xiao_esp32c6
build_type = release
build_flags =
    -DBOARD_XIAO_ESP32C6
    -DDROID_KE4

[env:chopper]
board = seeed_xiao_esp32c6
build_type = release
build_flags =
    -DBOARD_XIAO_ESP32C6
    -DDROID_CHOPPER

[env:r5]
board = seeed_xiao_esp32c6
build_type = release
build_flags =
    -DBOARD_XIAO_ESP32C6
    -DDROID_R5
