[platformio]
src_dir = src

[env]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.32
framework = arduino
monitor_speed = 115200
board = seeed_xiao_esp32c6

; Libraries
lib_deps =
    ; ESP-NOW is built into the ESP32 Arduino framework

[env:release]
build_type = release
build_flags =
    -DCORE_DEBUG_LEVEL=3
